### ISSUE TITLE
L5 Guard resurrection

### ISSUE THREAD

**Issue by MrBlinky** [Press-Play-On-Tape/PrinceOfArabia#175]
beta 23 release at  level 5 after collection a potion at the top room, the guard gets resurrected in this room when you return from the room at the left and instantly kills you.

When you kill the guard in this room, enter the room at the left and goback, the guard remains dead.
When you have collected aa potion in the secret room at the top and do the above, the guard  is ressurected and kills you instandly.

![recording_20230504155718](https://user-images.githubusercontent.com/4971163/236212248-6068a74b-51f7-4868-a1b6-eb72d2650ee5.gif)

**Comment by filmote** [comment]
Turns put you did not need to do the whole 'get a potion' thing.  It was just a case of timing .. if the live enemy still had actions in his queue to perform, then the transition would actually move the live enemy into the room.  Because he is alive, the rendering would ignore the dead guard.

![recording_20230505185143](https://user-images.githubusercontent.com/17228490/236404887-c852a294-7cf3-4722-9f0c-a787b6f51240.gif)

Fixed in Beta 024

**Comment by MrBlinky** [comment]
Confirmed!
